config/routes.rb
Rails.application.routes.draw do
  resources :albums
  resources :songs
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs, dependent: :restrict_with_error
  validates_presence_of :band
  validates_presence_of :title
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  validates_presence_of :title
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

    def new
      @album = Album.new
    end

    def create
      @album = Album.new(album_params)
      if @album.save
        redirect_to action: "index"
      else
        render action: "new"
      end
    end

    def show
   position = 0
   @album = Album.find(params[:id])
   @album.songs.each do |s|
     position += 1
     s.position = position
     s.save
   end
end

    def album_params
       params.require(:album).permit(:band, :title, :year, :duration)
      end

    def edit
      @album = Album.find(params[:id])
    end

    def update
      @album = Album.find(params[:id])
      if @album.update(album_params)
        redirect_to action: "index"
      else
        @songs = Song.all render action: "edit"
    end
  end

    def destroy
      @Albums = Album.all
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
      @albums = Album.order(:band, :title)
      @no_songs = Song.count
    end

    def new
      @albums = Album.select("id, band || ': ' || title as album_name").order(:band, :title)
    end

    def create
      @song = Song.new(song_params)
      if @song.save
        redirect_to action: "index"
      else
        @albums = Album.select("id, band || ': ' || title as album_name").order(:band, :title)
        render action: "new"
      end
    end

    def edit
      @song = Song.find(params[:id])
      @albums = Album.select("id, band || ': ' || title as album_name").order(:band, :title)
    end

    def update
      @song = Song.find(params[:id])
      if @song.update_attributes(song_params)
        redirect_to action: "index"
      else
        @albums = Album.select("id, band || ': ' || title as album_name").order(:band, :title)
        render action: "edit"
      end
    end

    def destroy
      Song.find(params[:id]).destroy
      redirect_to action: "index"
    end

    def song_params
      params.require(:song).permit(:album_id, :title, :duration)
    end
  end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/edit.html.erb
<div class="container">
  <br />
  <div class="row justify-content-center">
    <h2>Album ändern</h2>
  </div>
</div>
<div class="container">
  <%= form_for @album, url: {action: "update"}, class: "form-horizontal" do |f| %>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :band, "Band", class: "control-label" %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :band, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :title, "Titel", class: "control-label" %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :year, "Jahr", class: "control-label" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :year, class: "form-control" %>
      </div>
    </div>
    <br />
    <br />
    <div class="row">
      <div class="col-md-2"> </div>
      <div class="col-md-10">
        <%= f.submit "Album speichern", class: "btn btn-success" %>
        <%= link_to "Abbrechen", albums_path, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/albums/index.html.erb
<div class="container">
   <div class="row justify-content-center">
      <h2>Alben</h2>
     </div>
    </div>
    <div class="container">
       <table class="table table-hover">
          <thead class="thead-light">
             <tr>
               <th>Band</th>
                <th>Titel</th>
                 <th>Jahr</th>
                 <th colspan="2">
                 </th> </tr>
                </thead>
                <tbody>
                  <% @albums.each do |a| %>
                    <tr>
                       <td><%= a.band %>
                    </td>
                     <td><%= link_to a.title, album_path(a.id) %></td> <td><%= a.year %>
                    </td>
                    <td><%= a.songs.sum(:duration) %></td>
                      <td><%= a.songs.count %></td>
                     <td><%= link_to "Ändern", edit_album_path(a.id) %>
                    </td>
                     <td><%= link_to "Löschen", album_path(a.id), method: :delete %>
                    </td>
                   </tr>
                   <% end %>
                  </tbody>
                </table>
                <%= link_to "Album erfassen", new_album_path %><br />
                  <%= link_to "Songs", songs_path %>
                  </div>

app/views/albums/new.html.erb
<div class="container">
  <br />
  <div class="row justify-content-center">
    <h2>Album erfassen</h2>
  </div>
</div>
<div class="container">
  <%= form_for :album, url: {action: "create"}, class: "form-horizontal" do |f| %>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :band, "Band", class: "control-label" %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :band, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :title, "Titel", class: "control-label" %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :year, "Jahr", class: "control-label" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :year, class: "form-control" %>
      </div>
    </div>
    <br />
    <br />
    <div class="row">
      <div class="col-md-2"> </div>
      <div class="col-md-10">
        <%= f.submit "Album speichern", class: "btn btn-success" %>
        <%= link_to "Abbrechen", albums_path, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/albums/show.html.erb
<div class="container">
  <br />
  <div class="row justify-content-center">
    <h2><%= @album.band + " \"" + @album.title + "\"" + " (" + @album.year.to_s + ")" %></h2>
  </div>
</div>
<div class="container">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>Nr.</th>
        <th>Titel</th>
        <th>Dauer</th>
      </tr>
    </thead>
    <tbody>
      <% @album.songs.each do |a| %>
        <tr>
          <td><%= a.position %></td>
          <td><%= a.title %></td>
          <td><%= a.duration %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2">Gesamtdauer</td>
        <td><%= @album.duration %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to "Zurück", albums_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyVorbereitun</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<div class="container">
  <br />
  <div class="row justify-content-center">
    <h2>Song ändern</h2>
  </div>
</div>
<div class="container">
  <%= form_for @song, url: {action: "update"}, class: "form-horizontal" do |f| %>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :album_id, "Album", class: "control-label" %>
      </div>
      <div class="col-md-4">
        <%= f.collection_select :album_id, @albums, :id, :album_name, {}, {class: "form-control"} %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :title, "Titel", class: "control-label" %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :duration, "Dauer", class: "control-label" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :duration, class: "form-control" %>
      </div>
    </div>
    <br />
    <br />
    <div class="row">
      <div class="col-md-2"> </div>
      <div class="col-md-10">
        <%= f.submit "Song speichern", class: "btn btn-success" %>
        <%= link_to "Abbrechen", songs_path, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/songs/index.html.erb
<div class="container">
  <br />
  <div class="row justify-content-center">
    <h2>Songs</h2>
  </div>
</div>
<div class="container">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>Band</th>
        <th>Album</th>
        <th>Nr.</th>
        <th>Titel</th>
        <th>Dauer</th>
        <th colspan="2"> </th>
      </tr>
    </thead>
    <tbody>
      <% @albums.each do |a| %>
        <% a.songs.each do |s| %>
          <tr>
            <td><%= s.album.band %></td>
            <td><%= s.album.title %></td>
            <td><%= s.position %></td>
            <td><%= s.title %></td>
            <td><%= s.duration %></td>
            <td><%= link_to "Ändern", edit_song_path(s.id) %></td>
            <td><%= link_to "Löschen", song_path(s.id), method: :delete %></td>
          </tr>
        <% end %>
      <% end %>
      <tr><td colspan="7">Anzahl Songs: <%= @no_songs %></td></tr>
    </tbody>
  </table>
  <%= link_to "Song erfassen", new_song_path %><br />
  <%= link_to "Alben", albums_path %>
</div>

app/views/songs/new.html.erb
<div class="container">
  <br />
  <div class="row justify-content-center">
    <h2>Song erfassen</h2>
  </div>
</div>
<div class="container">
  <%= form_for :song, url: {action: "create"}, class: "form-horizontal" do |f| %>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :album_id, "Album", class: "control-label" %>
      </div>
      <div class="col-md-4">
        <%= f.collection_select :album_id, @albums, :id, :album_name, {}, {class: "form-control"} %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :title, "Titel", class: "control-label" %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-1">
        <%= f.label :duration, "Dauer", class: "control-label" %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :duration, class: "form-control" %>
      </div>
    </div>
    <br />
    <br />
    <div class="row">
      <div class="col-md-2"> </div>
      <div class="col-md-10">
        <%= f.submit "Song speichern", class: "btn btn-success" %>
        <%= link_to "Abbrechen", songs_path, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>